name: NodeJS

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cd all-in-lib
          npm install
          npm run build
      - if: github.ref == 'refs/heads/master'
        name: Publish
        run: |
          cd all-in-lib
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.ALL_IN_TOKEN }}" > .npmrc
          npm publish
